### PR TITLE
[Refiled] Add `decimalPatternDigits` to the list of allowed formats

### PR DESCRIPTION
**Pull request by amal-stack**
Refile of #47 as requested by @mosuem.

### CODE REVIEW

**Review by mosuem — APPROVED** [review]

**Comment by mosuem** [comment]
Can you press the merge button, or do I have to? I am curious.

**Comment by amal-stack** [comment]
@mosuem Looks like I cannot:

image

**Comment by amal-stack** [comment]
@mosuem Let me know if any other changes are required to go ahead with merging this PR.

**Comment by mosuem** [comment]
Thanks for the PR @amal-stack !

**Pull request merged**
